# basic
title: sophia
subtitle: 空山新雨后，天气晚来秋。
favicon: favicon.ico

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
avatar: https://avatars1.githubusercontent.com/u/7554242?v=3&s=460
banner_small: http://7xrcp8.com1.z0.glb.clouddn.com/banner-small.png
banner_large: http://7xrcp8.com1.z0.glb.clouddn.com/banner-large.png

# disqus
disqus_shortname: 

# social
social:
  github: https://github.com/SophiaChen
  weibo: http://www.weibo.com/sophia2ooo

# nav #
nav:
  home: .
  archive: archives
  about: about
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
